import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "", // generally used in child routes to ignore the template specified in parent layout title
    default: "child routes",
    template: "%s | Demo" // %s will be replaced by the title that we export from any child route. template is used to add prefix or suffix in title
  },
  description: 'Genereated by Next.js'
}


// we can export only a string, for title, if the return type is not Metadata
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
